[versions]

#AndroidX.
core = "1.9.0"
corektx = "1.9.0"
appcompat = "1.5.1"
runtimektx = "2.5.1"
constraintlayout = "2.1.4"
extjunit = "1.1.4"

#Compose.
compose = "1.3.2"
compose_nav = "2.5.3"
compose_viewmodel = "2.5.1"
compose_activity = "1.6.1"
compose_material3 = "1.0.1"
compose_constraintlayout = "1.1.0-alpha05"

#Exo
exo_core = "2.18.1"

#Test.
junit = "4.13.2"

[libraries]

#AndroidX.
androidx_core = { module = "androidx.core:core", version.ref = "core" }
androidx_corektx = { module = "androidx.core:core-ktx", version.ref = "corektx" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_runtimektx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "runtimektx" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx_extjunit = { module = "androidx.test.ext:junit", version.ref = "extjunit" }

#Compose.
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose_navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose_nav" }
compose_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose_viewmodel" }
compose_activity = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }
compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "compose_material3" }
compose_constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose_constraintlayout" }
compose_uitest = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose_junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose_manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

# Exo.
exoplayer_core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exo_core" }

#Test.
androidx_junit = { module = "junit:junit", version.ref = "junit" }

[bundles]
compose = ["compose.ui", "compose.toolingpreview", "compose.material3"]
composetest = ["compose.uitest", "compose.junit4", "compose.manifest"]
[plugins]
